### ISSUE TITLE
Slack 초대 부탁드립니다.

### ISSUE THREAD

**Issue by hangpark** [webpack-korea/webpack.js.org#28]
원본 레포에서 번역 관련 검색하다 작년 쯤 올리신 이슈 보고 넘어왔습니다! 번역에 동참하고 싶습니다. 커밋 로그 보니 작업 시작한 지 얼마 되지 않은 것 같네요^^ 같이 작업해나가면 좋을 것 같습니다.
제 메일은 hangpark@kaist.ac.kr 입니다. 감사합니다 😃

**Comment by Lutece** [comment]
안녕하세요 :) 참여해주셔서 감사합니다!
초대메일 발송해드렸습니다! 웹팩 버전업이 급상승하고, 문서화하는 프로세스가 중간에 바뀌면서,
프로젝트를 갈아엎는 작업을 진행했었습니다.
이전에 번역되었던 내용들이 아직 반영이 되지 않은 상태여서 
번거로우시겠지만, Closed된 Pull Request 내용 한번 확인해주시길 부탁드립니다!

번역 진행해주시면, 이슈에 서로 Assignees 등록해서 서로 확인하면서 진행하면 좋을거같아요 ㅎ 
프로젝트 진행 과정에 대한 의견 있으시면 언제든 말씀해주세요!!
참여 감사합니다! ㅎ

**Comment by Lutece** [comment]
@hangpark 
git 멤버 초대도 메일로 보내드렸습니다 :) 확인 부탁드립니다!

**Comment by hangpark** [comment]
@Lutece 감사합니다 :+1:
