### ISSUE TITLE
알파벳/숫자 이외 문자열 id 값 생성 오류

### ISSUE THREAD

**Issue by hangpark** [webpack-korea/webpack.js.org#34]
내부 anchor 링크 등에 사용되는 헤딩 태그 id 프로퍼티의 값은 타이틀 문자열로부터 자동으로 생성됩니다. 예를 들어 `Core Concepts`라는 타이틀은 `id="core-concepts"`와 같이 id 값이 생성되고 이를 통해 사이드바 등지에서 `#core-concepts`로 링크를 걸 수 있습니다.

그러나 내부 로직 상 알파벳 및 숫자를 제외한 모든 문자들의 연속된 문자열이 모두 `-`로 치환됩니다. 따라서 id 값을 변환할 때 `핵심 개념`은 `-`가, `핵심 Concepts`는 `-concepts`가 됩니다.

대부분 한글로 된 타이틀은 모두 `-`의 id 값을 가지게 되어 링크를 클릭할 때 같은 문서 내에 최상단 섹션으로 이동하는 버그가 생깁니다.

네비게이팅 기능이 굉장히 중요한 프로젝트이기 때문에 다국어 플랫폼에서 발생하는 이 버그를 수정하는 것이 좋을 것 같습니다.

**Comment by Lutece** [comment]
@hangpark 
반영 완료했습니다 :)
